#!/usr/bin/env bash
#install nginx
#connects through http
#print Hello World!

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

if [ -e /var/www/html/index.html ]; then
	if ! grep -q "Hello World" /var/www/html/index.html; then
		echo "Hello World!" > /var/www/html/index.html
	fi
else
	echo "Hello World!" > /var/www/html/index.html
fi

service nginx start
