#!/usr/bin/env bash
#install nginx
#connects through http
#print Hello World!
#configure to reditect 301

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html

REDIRECT="\\\tif (\$request_filename ~ redirect_me)\
 {\n\t\trewrite ^ https://linuxhint.com/find-ip-address-ubuntu/ permanent;\n\t}"

sudo sed -i "/server_name _;/a $REDIRECT" /etc/nginx/sites-enabled/default 

service nginx restart
