#!/usr/bin/env bash
# change port to 80

port1="listen 80 default_server"
port2="listen [::]:80 default_server ipv6only=on"

sed -i "s/listen 8080 default_server/$port1/" /etc/nginx/sites-enabled/default
sed -i "s/listen \[::\]:8080 default_server ipv6only=on/$port2/" /etc/nginx/sites-enabled/default


service nginx restart
