#!/usr/bin/env bash
#display user's name, id, root dir from /etc/passwd


while IFS=: read -r fs ss th ft ff sx sv;
do
	echo "The user $fs is part of the $ft gang, lives in $sx and rides $sv. $th place is protected by the passcode $ss, more info about the user here: $ff"
done < /etc/passwd 
